### ISSUE TITLE
Read resource

### ISSUE THREAD

**Issue by ppppppw** [squad-shopcarts/shopcarts#15]
**As a** Developer
**I need** to read the data from the existing shopping cart
**So that** I can get the current shopping cart data including items and prices

**Details & Assumptions:** 
* All read data shall be shown in the correct areas to the user.
* If the action of read the data returns no result, it means that the user's shopping cart is not created, which report as an error to the developer (every user should have a shopping cart linked to him/her).
* All data read should be up-to-date.

**Acceptance Criteria:**

```gherkin
Given a user_id from a customer
When I perform read query on the customer's shopping cart
Then I should see all the added products information and the price information if the shopping cart is not empty; or if it is empty, I should still retrieve the result that the shopping cart database exists, but there's no product in it.
```

**Comment by goilfrend** [comment]
Resource means 'shopping cart' :)
