### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by ppppppw** [squad-shopcarts/shopcarts#25]
**As a** Developer
**I need** to create and update README.md file  
**So that** users and other developers will know how to run the code and how the code works.

**Details & Assumptions:** 
* The README.md should include instructions on all calls available and expected inputs
* It will tell the user how to run and test the code so that users will know how it works.

**Acceptance Criteria:**

```gherkin
Given available model.py and its test available in the repository
When a developer want to run the test on the model.py
Then the developer can read the README.md to learn about the instructions/steps to take to run the model.
```

**Comment by itz-JR** [comment]
Meeting consensus: if you wrote the code document how to use it and we'll have a collective readme
