### ISSUE TITLE
product validation check when clicking on checkout button

### ISSUE THREAD

**Issue by lmcdhr** [squad-shopcarts/shopcarts#5]
**As a** User 
**I need** the system to check the validation of my shopping cart before checkout  
**So that** I can find out if there is unavailable product in my cart and proceed to the checkout procedures safely  

**Details & Assumptions:** 
* We will only have one warehouse, every orders will be processed in that warehouse
* We will only check if there is sufficient stock of specific goods in the warehouse

**Acceptance Criteria:**

```gherkin
Given customer James adding 4 apples in his shopping cart and would like to checkout
When there are only 3 apples in our warehouse
Then when clicking on checkout button, he should be reminded that there is no enough apples for him 
And the system should ask him to input another quantity 
```

**Comment by goilfrend** [comment]
change warehouse to inventory for consistency please
