### ISSUE TITLE
delete a shopcart item

### ISSUE THREAD

**Issue by AubreySong1997** [squad-shopcarts/shopcarts#8]
**As a**  Developer
**I need**  to delete certain shopcart when necessary
**So that** the storage won't be wasted

**Assumptions:**
* There is at least one shop cart to be deleted 
* One user can only have one shopcart

**Accpetance Criteria:**
```
Given a user_id  
Then delete the shopcart assigned to that user_id
Then delete the user_id
```

**Comment by itz-JR** [comment]
Just commenting from discussion: we don't think we need to delete a shopping cart. We will just empty the shopping cart and leave it in existence for now. 

We only see a need to delete a shopping cart if a user is deleted from the system which we believe is outside our scope.
